/*
 * Copyright (C) 2018 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef TMEM_UT_CMD_H
#define TMEM_UT_CMD_H

enum TMEM_DEVICE_UT_COMMAND {
	TMEM_MANUAL_CMD_RESERVE_START = 0,

	TMEM_DEVICE_COMMON_OPERATION_START = TMEM_MANUAL_CMD_RESERVE_START,
	TMEM_DEVICE_COMMON_OPERATION_SSMR_ALLOC = 0,
	TMEM_DEVICE_COMMON_OPERATION_SSMR_RELEASE = 1,
	TMEM_DEVICE_COMMON_OPERATION_SESSION_OPEN = 2,
	TMEM_DEVICE_COMMON_OPERATION_SESSION_CLOSE = 3,
	TMEM_DEVICE_COMMON_OPERATION_REGION_ON = 4,
	TMEM_DEVICE_COMMON_OPERATION_REGION_OFF = 5,
	TMEM_DEVICE_COMMON_OPERATION_CHUNK_ALLOC = 6,
	TMEM_DEVICE_COMMON_OPERATION_CHUNK_FREE = 7,
	TMEM_DEVICE_COMMON_OPERATION_ION_ALLOC_FREE = 8,
	TMEM_DEVICE_COMMON_OPERATION_RESERVED_2 = 9,
	TMEM_SECMEM_SVP_SSMR_ALLOC = TMEM_DEVICE_COMMON_OPERATION_START,
	TMEM_SECMEM_SVP_SSMR_RELEASE = 1,
	TMEM_SECMEM_SVP_SESSION_OPEN = 2,
	TMEM_SECMEM_SVP_SESSION_CLOSE = 3,
	TMEM_SECMEM_SVP_REGION_ON = 4,
	TMEM_SECMEM_SVP_REGION_OFF = 5,
	TMEM_SECMEM_SVP_CHUNK_ALLOC = 6,
	TMEM_SECMEM_SVP_CHUNK_FREE = 7,
	TMEM_SECMEM_SVP_ION_ALLOC_FREE = 8,
	TMEM_SECMEM_SVP_RESERVED_2 = 9,
	TMEM_DEVICE_COMMON_OPERATION_END = 60,

	TMEM_REGION_STATUS_DUMP = 61,
	TMEM_SECMEM_SVP_DUMP_INFO = 62,
	TMEM_SECMEM_DYNAMIC_DEBUG_ENABLE = 65,
	TMEM_SECMEM_DYNAMIC_DEBUG_DISABLE = 66,
	TMEM_SECMEM_FORCE_HW_PROTECTION = 67,

	TMEM_MANUAL_CMD_RESERVE_END = 99,

	SECMEM_UT_PROC_BASE = 300,
	SECMEM_UT_PROC_BASIC = SECMEM_UT_PROC_BASE,
	SECMEM_UT_PROC_SIMPLE_ALLOC = 301,
	SECMEM_UT_PROC_UNORDERED_SIZE = 302,
	SECMEM_UT_PROC_ALIGNMENT = 303,
	SECMEM_UT_PROC_SATURATION = 304,
	SECMEM_UT_PROC_SATURATION_STRESS = 305,
	SECMEM_UT_PROC_REGION_DEFER = 306,
	SECMEM_UT_PROC_REGION_ONLINE_CNT = 307,
	SECMEM_UT_PROC_REGION_STRESS = 308,
	SECMEM_UT_PROC_ALLOC_MULTITHREAD = 309,
	SECMEM_UT_PROC_ALL = 399,
	SECMEM_UT_PROC_MAX = SECMEM_UT_PROC_ALL,

#ifdef TCORE_MEMORY_LEAK_DETECTION_SUPPORT
	TMEM_MEMORY_LEAK_DETECTION_CHECK = 900,
#endif
	TMEM_PROFILE_DUMP = 901,

	TMEM_RUN_ALL_SUITES = KERN_UT_RESERVED_COMMAND_RUN_ALL_SUITES,
};

#endif /* end of TMEM_UT_CMD_H */
